version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/battlesnake
hooks:
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/prerequirements.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/app_run.sh
      timeout: 300
      runas: ubuntu